name: Build RunViso Runtime Image

on:
  push:
    branches: [ main ] # Or your default branch
    # Trigger only if the RunViso files in the root directory change
    paths:
      - 'RunViso-Dockerfile'
      - 'RunViso-Supervisord.conf'
      - 'RunViso-Caddyfile'
      - 'RunViso-SetupGuide.ipynb'
      - '.github/workflows/build-runviso.yml' # Also trigger if the workflow itself changes
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # Use your GitHub repository secrets for credentials
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push RunViso image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the root
          file: ./RunViso-Dockerfile # Point to the Dockerfile in the root
          push: true
          tags: remphan/runviso:latest # Use the correct repo name in the tag
          no-cache: true # Ignore build cache to resolve potential inconsistencies
          # Optional: Add build args if needed
          # build-args: |
          #   SOME_ARG=value
